M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2026-01-23T17:01:36+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-23T17:01:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X-2.89Y10.645
X2.89Y10.645
M30
