M48
; DRILL file {KiCad 8.0.8} date 2025-02-18T14:47:54+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-18T14:47:54+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.710
%
G90
G05
T1
X0.0Y-0.975
T2
X-1.27Y-3.85
X0.0Y-3.85
X1.27Y-3.85
M30
