M48
; DRILL file {KiCad 8.0.2-1} date 2024-12-19T17:28:41+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-19T17:28:41+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.080
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.100
%
G90
G05
T1
X-25.0Y10.0
X-25.0Y-10.0
T2
X25.0Y10.0
X25.0Y-10.0
M30
