M48
; DRILL file {KiCad 9.0.0} date 2025-02-28T17:55:09+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-28T17:55:09+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X0.92Y0.0
X11.08Y0.0
T2
X6.0Y0.0
M30
